### ISSUE TITLE
Updating

### ISSUE THREAD

**Issue by mattben** [UV-CDAT/vcdat#106]
@chaosphere2112 What is the process for doing an updated after merging and pulling from vcs-widgets and vcdat master? Can you also updated this page. https://github.com/UV-CDAT/vcdat/wiki/Updating See #107 
    
cd ~/vcdat
    git fetch --all
    git pull upstream master
    ./scripts/setup_mac.sh

    cd ~/vcs-widgets
    git fetch --all
    git pull upstream master
    
    source activate vcdat
    npm install

    cd ~/vcdat
    npm link vcs-widgets
    ./scritps/autorun.sh

** But **

    Loading virtual environment...
    vcs-widgets is not symlinked, so will not be automatically watched.
      0% compiling
    Webpack is watching the files…

**Comment by chaosphere2112** [comment]
@mattben I need to add you to the `vcs-widgets` package on npm; have you set up a username on there?

**Comment by mattben** [comment]
@chaosphere2112 yes `mattben`

**Comment by James-Crean** [comment]
I believe this may be caused by one of two things:
* It could be that ```npm link``` was not ran inside the vcs-widgets directory prior to running 
```npm link vcs-widgets```
* It could also be possible that npm is linking to the wrong path. In that case you can create a folder further up the directory tree that will hold the links, then set that folder as the 'prefix' value according the the npm documentation [here](https://docs.npmjs.com/cli/link)

General documentation for linking vcs-widgets is here: https://github.com/UV-CDAT/vcdat/wiki/Releasing-vcs-widgets
