### ISSUE TITLE
drop pip in install process

### ISSUE THREAD

**Issue by doutriaux1** [UV-CDAT/vcdat#21]
I read some not so good interaction between pip and conda, in general if we should drop usage of pip in favor of conda.

**Comment by doutriaux1** [comment]
in the same lines, why do we need brew? We should check if we can't replace brew by conda where possible

**Comment by doutriaux1** [comment]
example:
```
anaconda search -t conda npm
Using Anaconda Cloud api site https://api.anaconda.org
Run 'anaconda show <USER/PACKAGE>' to get more details:
/Users/doutriaux1/anaconda2/lib/python2.7/site-packages/requests/packages/urllib3/connectionpool.py:791: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.org/en/latest/security.html
  InsecureRequestWarning)
Packages:
     Name                      |  Version | Package Types   | Platforms      
     ------------------------- |   ------ | --------------- | ---------------
     auto/npm_watcher          |      0.1 | conda           | linux-64       
                                          : UNKNOWN
     cpcloud/npm               |   1.4.12 | conda           | linux-64, win-32, win-64, linux-32, osx-64
                                          : Node Package Manager
     jakirkham/npm             |   1.4.12 | conda           | linux-64, osx-64
Found 3 packages
```

**Comment by chaosphere2112** [comment]
@doutriaux1 Users won't need brew/npm at all; that's just a developer dependency to assemble and minify the javascript. For releases, a minified version of the JS and CSS will be built as part of the distributed package (in conda). As for pip, it was mostly because I already knew how to set up a requirements file for pip vs conda which I just learned how to do. If you want to migrate the requirements document/setup script/autorun script to conda, we're accepting pull requests :wink:

**Comment by chaosphere2112** [comment]
(also I haven't had any issues with pip + conda, since I'm using the pip provided by conda)

**Comment by doutriaux1** [comment]
@chaosphere2112 see #24 I'm holding you to your word on PRs 😜

**Comment by doutriaux1** [comment]
npm could use `conda` but it seems to conflict with uvcdat (numpy?)
